nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: 
          - 'http://localhost:5173'
          - 'https://mon-projet-eosin.vercel.app'
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: false
            allow_origin: 
              - 'http://localhost:5173'
              - 'https://mon-projet-eosin.vercel.app'
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_credentials: true
            max_age: 3600
