nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:5173']  # Remplace par l'URL de ton front-end
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': ~  # Permet CORS pour toutes les routes commençant par /api/
